// <auto-generated />
using Euroskills_2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euroskills_2018.Migrations
{
    [DbContext(typeof(szamkaDbContext))]
    [Migration("20251105120625_sqlite.local_migration_162")]
    partial class sqlitelocal_migration_162
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Euroskills_2018.Models.Orszag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orszagnev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orszag");
                });

            modelBuilder.Entity("Euroskills_2018.Models.Szakma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Szakmanev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Szakma");
                });

            modelBuilder.Entity("Euroskills_2018.Models.Versenyzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrszagId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SzakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SzakmaId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pont")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId1");

                    b.HasIndex("SzakmaId1");

                    b.ToTable("Versenyzo");
                });

            modelBuilder.Entity("Euroskills_2018.Models.Versenyzo", b =>
                {
                    b.HasOne("Euroskills_2018.Models.Orszag", null)
                        .WithMany("Versenyzok")
                        .HasForeignKey("OrszagId1");

                    b.HasOne("Euroskills_2018.Models.Szakma", null)
                        .WithMany("Versenyzok")
                        .HasForeignKey("SzakmaId1");
                });

            modelBuilder.Entity("Euroskills_2018.Models.Orszag", b =>
                {
                    b.Navigation("Versenyzok");
                });

            modelBuilder.Entity("Euroskills_2018.Models.Szakma", b =>
                {
                    b.Navigation("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
